chat/chat/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from users.views import LoginUserView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LoginUserView.as_view(), name='user-login'),
    path('', include('users.urls')),
    path('', include('home.urls')),
    path('', include('messages.urls')),
]

chat/home/urls.py
from django.urls import path, re_path, include

from . import views

app_name = "home_app"

urlpatterns = [
    path('panel/', views.HomePage.as_view(), name='panel'),
]

chat/users/urls.py
from django.urls import path, re_path, include


from .views import UserRegisterView, LoginUserView, LogoutUserView
app_name = "users_app"

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='user-register'),
    path('login/', LoginUserView.as_view(), name='user-login'),
    path('logout/', LogoutUserView.as_view(), name='user-logout'),
]

chat/home/models.py
from django.db import models

# Create your models here.

chat/home/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse

from users.models import User

from django.views.generic import (
    TemplateView
)

class HomePage(LoginRequiredMixin, TemplateView):
    template_name = "home/index.html"
    login_url = reverse_lazy('users_app:user-login')
    
    def get_context_data(self, **kwargs):
        context = super(HomePage, self).get_context_data(**kwargs)
        context['users'] = User.objects.all()
        return context

chat/templates/home/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <style></style>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Prueba backend Django</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'css/styles_chat.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="#page-top">Welcome:   {{ user.get_full_name }}</a>
                <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'users_app:user-logout' %}">Sign Off</a></li>
                    </ul>
                </div>
            </div>
        </nav>
          <!-- Masthead-->
        <header class="masthead text-center" style="height: 200px;">
            <div class="container d-flex align-items-center flex-column">
            {% block header%}
                <h1>ROOM CHAT</h1>
            {% endblock %}
            </div>
        </header>
        
        <div class="container py-5 px-4">
            <!-- For demo purpose-->
            <div class="row rounded-lg overflow-hidden shadow">
              <!-- Users box-->
              <div class="col-5 px-0 overflow-hidden">
                <div class="bg-white">
          
                  <div class="bg-gray px-4 py-2 bg-light">
                    <p class="h5 mb-0 py-1">Recent Users</p>
                  </div>
                  <!-- Users-->
                  <div class="messages-box">
                    <div class="list-group rounded-0">
                      <a class="list-group-item list-group-item-action active text-white rounded-0">
                        {% for user in users %}
                        <div class="media" style="padding-top:10px;"><img src="https://static.vecteezy.com/system/resources/previews/000/568/134/non_2x/vector-chat-dialogue-icon.jpg" alt="user" width="50" class="rounded-circle">
                          <div class="media-body ml-4">
                            <div class="d-flex align-items-center justify-content-between mb-1">
                              <h6 class="mb-0" style="padding-top:10px;">{{ user.username }}</h6>
                            </div>
                            <p class="font-italic mb-0 text-small">
                                {% if user.last_login%} 
                                    {{user.last_login}} 
                                {% else %} 
                                    No hay datos de inicio de sesión
                                {% endif %} 
                            </p>
                          </div>
                        </div>
                      </a>
                      {% endfor %}
                    </div>
                  </div>
                <!-- End Users-->
                </div>
              </div>
              <!-- Chat Box-->
          
                <!-- Sender Message-->
                <div class="media w-50 mb-3">
                    <div class="media-body ml-3 overflow-auto">
                        <div class="bg-light rounded py-2 px-3 mb-2 ">
                            <div class="text-small mb-0 text-muted  overflow-auto" style="height: 542px;">
                                <ul class="chat_messages text-right"></ul>
                            </div>
                        </div>
                    </div>
                </div>
          
                
                <!-- Typing area -->
                <form action="POST" class="bg-light">{% csrf_token %}
                  <div class="input-group">
                    <input type="text" placeholder="Type a message" aria-describedby="button-addon2" style="width:80%;" class="form-control rounded-0 border-0 py-4 bg-light message_text">
                    <div class="input-group-append">
                      <button  type="submit" class="btn btn-link send-text"> <i class="fa fa-paper-plane"></i></button>
                    </div>
                  </div>
                </form>
            </div>
        </div>

        <!-- Footer-->
        <footer class="footer text-center">
            <div class="container">
                <div class="row">
                    <!-- Footer Social Icons-->
                    <div class="col-lg-12 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">My Social Media</h4>
                        <a class="btn btn-outline-light btn-social mx-1" href="https://www.linkedin.com/in/jorge-cer%C3%B3n-unigarro-02284459/"><i class="fab fa-fw fa-linkedin-in"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="https://www.facebook.com/jorge.ceron87/"><i class="fab fa-fw fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="https://twitter.com/ceron87"><i class="fab fa-fw fa-twitter"></i></a>
                    </div>
                    <!-- Footer About Text-->
                </div>
            </div>
        </footer>
        <!-- Copyright Section-->
        <div class="copyright py-4 text-center text-white">
            <div class="container">
                <small>
                    Copyright &copy; 
                    <!-- This script automatically adds the current year to your website footer-->
                    <!-- (credit: https://updateyourfooter.com/)-->
                    <script>
                        document.write(new Date().getFullYear());
                    </script>
                </small>
            </div>
        </div>
        <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes)-->
        <div class="scroll-to-top d-lg-none position-fixed">
            <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top"><i class="fa fa-chevron-up"></i></a>
        </div>
       
       
        <!-- Bootstrap core JS-->
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.1/anime.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
         <!-- Scripst DATA-->
        <script>
            const userId = '{{ user.id }}';
            const username = '{{ user.username }}'; 
            sessionStorage.setItem('user_id', userId);
            sessionStorage.setItem('username', username);
        </script>
        <script type="module" src="{% static 'js/index.js' %}"></script>
    </body>
</html>